project:
  type: website
  output-dir: docs
resources:
  - CNAME
website:
  favicon: favicon.png
  page-navigation: true
  repo-branch: main
  repo-url: https://github.com/MrGeislinger/victorsothervector
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/MrGeislinger
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/victorsothervector.bsky.social
      - icon: linkedin 
        href: https://www.linkedin.com/in/mrgeislinger/
    left:
      - icon: house
        text: "Home"
        file: index.qmd
      - icon: book
        text: "My Reading"
        href: books/
      - icon: substack 
        href: https://victorsothervector.substack.com/?r=2fco1e
        text: "Newsletter"